### ISSUE TITLE
xsecsize_t macro replaced next xmlsec

### ISSUE THREAD

**Issue by saunaants** [open-eid/libdigidocpp#163]
https://issues.apache.org/jira/browse/SANTUARIO-474

https://github.com/open-eid/libdigidocpp/blob/5034207e1e8e1ce31779f5956284adf60d605736/src/xml/SecureDOMParser.cpp#L96

**Comment by metsma** [comment]
And how does it affect us?

**Comment by david-geiger** [comment]
With latest xml-security-c 2.0.1 libdigidocpp doesn't build anymore due to:

> /home/iurt/rpmbuild/BUILD/libdigidocpp-3.13.6/src/xml/SecureDOMParser.cpp: In static member function 'static void digidoc::SecureDOMParser::calcDigestOnNode(digidoc::Digest*, const string&, xercesc_3_2::DOMDocument*, xercesc_3_2::DOMNode*)':
/home/iurt/rpmbuild/BUILD/libdigidocpp-3.13.6/src/xml/SecureDOMParser.cpp:98:5: error: 'xsecsize_t' was not declared in this scope
     xsecsize_t bytes = 0;
     ^~~~~~~~~~
/home/iurt/rpmbuild/BUILD/libdigidocpp-3.13.6/src/xml/SecureDOMParser.cpp:98:5: note: suggested alternative: 'ssize_t'
     xsecsize_t bytes = 0;
     ^~~~~~~~~~
     ssize_t
/home/iurt/rpmbuild/BUILD/libdigidocpp-3.13.6/src/xml/SecureDOMParser.cpp:99:12: error: 'bytes' was not declared in this scope
     while((bytes = c14n.outputBuffer(buffer, 1024)) > 0)
            ^~~~~
make[2]: *** [src/CMakeFiles/digidocpp_priv.dir/build.make:440: src/CMakeFiles/digidocpp_priv.dir/xml/SecureDOMParser.cpp.o] Error 1
make[2]: Leaving directory '/home/iurt/rpmbuild/BUILD/libdigidocpp-3.13.6/build'
make[2]: *** Waiting for unfinished jobs....


Regards,
David

**Comment by arekm** [comment]
Based on
https://github.com/apache/santuario-cpp/commit/106e0189ff3c5530379d1478d95d1b08f8d2d81d
looks like the fix is to use XMLSize_t (and checking if XMLSize_t or xsecsize_t type exists).

**Comment by metsma** [comment]
ac223f174d0b728f2010b187a425b7e26f334cd3
